### ISSUE TITLE
Todo: GraphQL

### ISSUE THREAD

**Issue by Flusinerd** [Datenlotse/OFO-Backend#1]
- [x] EventUser: Add Platform(s)
- [x] EventUser: Add Date(s)

**Comment by Flusinerd** [comment]
- [ ] EventUser: Add Platform: Allow for creating and linking in same mutation
